### ISSUE TITLE
运行roslaunch yolo_ros yolo_service.launch之后，能将检测框显示出来吗

### ISSUE THREAD

**Issue by tulingcheng86** [jianhengLiu/yolo_ros#3]
我看了另一个issue的内容，我能输出 rostopic eo /untracked_info的检测内容
支持可视化吗

**Comment by jianhengLiu** [comment]
印象中我把可视化代码注释了，可以取消注释尝试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月21日(周二) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jianhengLiu/yolo_ros] 运行roslaunch yolo_ros yolo_service.launch之后，能将检测框显示出来吗 (Issue #3)




 
我看了另一个issue的内容，我能输出 rostopic eo /untracked_info的检测内容
 支持可视化吗

**Comment by tulingcheng86** [comment]
> 印象中我把可视化代码注释了，可以取消注释尝试一下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月21日(周二) 下午5:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [jianhengLiu/yolo_ros] 运行roslaunch yolo_ros yolo_service.launch之后，能将检测框显示出来吗 (Issue #3) 我看了另一个issue的内容，我能输出 rostopic eo /untracked_info的检测内容 支持可视化吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Σ(O_O)回的好快。好的我去看看取消注释试试

**Comment by tulingcheng86** [comment]
> 印象中我把可视化代码注释了，可以取消注释尝试一下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月21日(周二) 下午5:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [jianhengLiu/yolo_ros] 运行roslaunch yolo_ros yolo_service.launch之后，能将检测框显示出来吗 (Issue #3) 我看了另一个issue的内容，我能输出 rostopic eo /untracked_info的检测内容 支持可视化吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

取消注释后 解决了

**Comment by tulingcheng86** [comment]
能显示检测框了
